### ISSUE TITLE
#![feature(custom_attribute)] prevents compilation on stable

### ISSUE THREAD

**Issue by Electron100** [blm768/wasm-bindgen-console-logger#1]
This package cannot compile on stable Rust due to the use of `#![feature(custom_attribute)] `. It's unclear (to my anyway) why this feature is specified. If it is removed, the package compiles without issue on stable (1.32)

Based on the latest discussion at https://github.com/rust-lang/rust/issues/29642, it appears that the `custom_attribute` feature is likely to be removed from nightly soon, anyway.

**Comment by blm768** [comment]
Good catch. I copied the feature flag out of an older project that been started back when `#![feature(custom_attribute)]` was necessary for `wasm_bindgen`, but it looks like that's no longer the case.

**Comment by blm768** [comment]
This should be fixed with the latest release. Thanks for reporting the issue!
